version: "3.8"

services:
  app:
    image: mcr.microsoft.com/dotnet/sdk:8.0
    volumes:
      - .:/app
    working_dir: /app
    ports:
      - "5008:5008"
    command: bash -c "dotnet restore && dotnet run"
